### ISSUE TITLE
Recommendation for modifying response

### ISSUE THREAD

**Issue by lucasyvas** [gengteng/axum-valid#25]
Great library! I'm trying to use it for an API that returns JSON and I'm wondering what the preferred way would be to consume the error string yielded from the Valid extractor, but transform it into a JSON response. Ideally I'd like to do this in one way for anything that the extractor invalidates on any route.

**Comment by gengteng** [comment]
To return JSON responses when the Valid extractor fails, enable the into_json feature for the axum-valid crate. Additionally, if you want to change the HTTP response status code to 422 when validation errors occur, you can enable the 422 feature. If you have more complex requirements, feel free to discuss them!

```toml
[dependencies]
axum-valid = { version = "0.18.0", features = ["into_json", "422"] }
```
